const countries = [
  { 1: "Nicaragua" },
  { 2: "Finland" },
  { 3: "Thailand" },
  { 4: "Greece" },
  { 5: "Andorra" },
  { 6: "Panama" },
  { 7: "Bolivia" },
  { 8: "Luxembourg" },
  { 9: "Algeria" },
  { 10: "Liechtenstein" },
  { 11: "Mongolia" },
  { 12: "Indonesia" },
  { 13: "Benin" },
  { 14: "United Arab Emirates" },
  { 15: "Congo" },
  { 16: "Bulgaria" },
  { 17: "Dominican Republic" },
  { 18: "China" },
  { 19: "Costa Rica" },
  { 20: "Slovenia" },
  { 21: "Tanzania" },
  { 22: "Antigua and Barbuda" },
  { 23: "Solomon Islands" },
  { 24: "Ethiopia" },
  { 25: "Mozambique" },
  { 26: "Cameroon" },
  { 27: "Saint Lucia" },
  { 28: "Moldova" },
  { 29: "Fiji" },
  { 30: "Antigua and Barbuda" },
  { 31: "Czech Republic" },
  { 32: "Afghanistan" },
  { 33: "Slovakia" },
  { 34: "Lesotho" },
  { 35: "Sudan, South" },
  { 36: "United Kingdom" },
  { 37: "Uruguay" },
  { 38: "Palau" },
  { 39: "Haiti" },
  { 40: "Swaziland" },
  { 41: "Mauritania" },
  { 42: "Bahrain" },
  { 43: "Samoa" },
  { 44: "Jordan" },
  { 45: "El Salvador" },
  { 46: "Korea, South" },
  { 47: "Haiti" },
  { 48: "Liberia" },
  { 49: "Qatar" },
  { 50: "South Africa" },
  { 51: "Honduras" },
  { 52: "Kyrgyzstan" },
  { 53: "Denmark" },
  { 54: "Korea, South" },
  { 55: "Liberia" },
  { 56: "Syria" },
  { 57: "Marshall Islands" },
  { 58: "Chile" },
  { 59: "Indonesia" },
  { 60: "Syria" },
  { 61: "Cyprus" },
  { 62: "Mexico" },
  { 63: "Denmark" },
  { 64: "Macedonia" },
  { 65: "Uganda" },
  { 66: "Ukraine" },
  { 67: "Germany" },
  { 68: "Haiti" },
  { 69: "Benin" },
  { 70: "Bahrain" },
  { 71: "Malaysia" },
  { 72: "Belgium" },
  { 73: "Iceland" },
  { 74: "Uganda" },
  { 75: "Egypt" },
  { 76: "Burkina Faso" },
  { 77: "Vanuatu" },
  { 78: "Grenada" },
  { 79: "Croatia" },
  { 80: "Madagascar" },
  { 81: "Georgia" },
  { 82: "Nepal" },
  { 83: "San Marino" },
  { 84: "Belarus" },
  { 85: "Sri Lanka" },
  { 86: "Finland" },
  { 87: "Costa Rica" },
  { 88: "Kosovo" },
  { 89: "Brunei" },
  { 90: "Dominican Republic" },
  { 91: "Albania" },
  { 92: "Morocco" },
  { 93: "Poland" },
  { 94: "The Bahamas" },
  { 95: "Portugal" },
  { 96: "Slovenia" },
  { 97: "Mali" },
  { 98: "Turkey" },
  { 99: "Chile" },
  { 100: "Hungary" },
];

export default countries;
